/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactMe: typeof import('./src/components/main/contact-me/ContactMe.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Email: typeof import('./src/components/profiles/contact/Email.vue')['default']
    Experience: typeof import('./src/components/main/experience/Experience.vue')['default']
    FixedStick: typeof import('./src/components/common/FixedStick.vue')['default']
    Github: typeof import('./src/components/profiles/contact/Github.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Introduction: typeof import('./src/components/main/introduction/Introduction.vue')['default']
    Main: typeof import('./src/components/main/Main.vue')['default']
    NavigationCard: typeof import('./src/components/navigation-card/NavigationCard.vue')['default']
    Profiles: typeof import('./src/components/profiles/Profiles.vue')['default']
    Project: typeof import('./src/components/main/project/Project.vue')['default']
    ProjectDetail: typeof import('./src/components/main/project/ProjectDetail.vue')['default']
    QQ: typeof import('./src/components/profiles/contact/QQ.vue')['default']
    RichCard: typeof import('./src/components/common/RichCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCartList: typeof import('./src/components/common/ShowCartList.vue')['default']
    Skill: typeof import('./src/components/main/skill/Skill.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    Welcome: typeof import('./src/components/main/welcome/Welcome.vue')['default']
  }
}
